# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='This is the default description for dojos'),
            preserve_default=False,
        ),
    ]
